steps:
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]/path/to/your/jdk11"
  displayName: 'Set JAVA_HOME manually'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
